FROM registry.access.redhat.com/ubi9/ubi-micro@sha256:2044e2ca8e258d00332f40532db9f55fb3d0bfd77ecc84c4aa4c1b7af3626ffb

WORKDIR /go/src/app
COPY ./hello-go .

USER nobody
EXPOSE 8080
CMD ["./hello-go"]
