FROM registry.access.redhat.com/ubi9/ubi-micro@sha256:37b939d8b86b5cad34ce6212480c88b4d731272116d57c46b4acce0516e7d8e6

WORKDIR /go/src/app
COPY ./hello-go .

USER nobody
EXPOSE 8080
CMD ["./hello-go"]
