apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-cicd
resources:
- trigger-binding.yaml
- trigger-template.yaml
- trigger.yaml
- event-listener.yaml
- event-listener-route.yaml
